name: kehadiranmu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  carousel_slider: ^4.1.1
  cloud_firestore: 3.1.12
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.14
  firebase_core: 1.12.0
  firebase_storage: 10.2.12
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.2
  flutter_svg: ^1.0.3
  flutterfire_cli: 0.2.0
  get: 4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  splash_screen_view: ^3.0.0
  table_calendar: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

splash_screen_view:
  color: "#ffffff"   
